# Build Stage
FROM jelastic/maven:3.9.5-openjdk-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package

# Runtime Stage
FROM openjdk:21-slim
WORKDIR /app

COPY --from=build /app/target/minitwit-java-simulator-api.jar app.jar

EXPOSE 5001
CMD ["java", "-jar", "app.jar"]