services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "minitwit"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    # mount ONLY the schema init—no persistent data volume
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  minitwit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "jdbc:mysql://mysql:3306/minitwit?user=root"
    depends_on:
      mysql:
        condition: service_healthy

  simulator-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "jdbc:mysql://mysql:3306/minitwit?user=root"
    depends_on:
      mysql:
        condition: service_healthy
