filebeat.inputs:
  - type: log
    paths:
      - /data/logs/*.log
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

output.elasticsearch:
  hosts: ["http://161.35.71.145:9200"]  # replace localhost with your logging droplet IP

setup.kibana:
  host: "http://161.35.71.145:5601"  # replace <MONITOR_HOST> accordingly