# monitoring/docker-compose.yml

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=devops
      - GF_SECURITY_ADMIN_PASSWORD=devops123
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../grafana/provisioning/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    command: ["--path.rootfs=/host"]
    volumes:
      - /:/host:ro
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    # platform: linux/amd64           # if on ARM; drop if on x86
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m   # ↓ limit heap to 256 MiB
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    # platform: linux/amd64           # if on ARM
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
    volumes:
      - type: bind
        source: ./kibana.yml
        target:   /usr/share/kibana/config/kibana.yml
        read_only: true
      - type: bind
        source: ./provisioning
        target: /usr/share/kibana/config/provisioning
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  es-data:
    driver: local