global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['68.183.210.76:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['68.183.210.76:8080']

  - job_name: 'app-jmx'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - 'minitwitdevops.live:9404'   # JMX on minitwit
          - 'minitwitdevops.live:9405'   # JMX on simulator

  - job_name: 'app-http'
    scheme: https                # ← switch to HTTPS
    tls_config:
      insecure_skip_verify: true # ← if you don’t have a CA-signed cert yet
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'minitwitdevops.live:9091'
          - 'minitwitdevops.live:9092'

  - job_name: 'app-node-exporter'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['minitwitdevops.live:9101']

  - job_name: 'app-cadvisor'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['minitwitdevops.live:8081']
