# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']

#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:8080']

#   - job_name: 'app-jmx'
#     static_configs:
#       - targets:
#           - 'minitwit:9404'
#           - 'simulator-api:9404'

# monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['68.183.210.76:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['68.183.210.76:8080']

  - job_name: 'app-jmx'
    static_configs:
      - targets:
          - '161.35.71.145:9404'   # JMX on minitwit
          - '161.35.71.145:9405'   # JMX on simulator
