global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['68.183.210.76:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['68.183.210.76:8080']

  - job_name: 'app-jmx'
    static_configs:
      - targets:
          - '161.35.71.145:9404'   # JMX on minitwit
          - '161.35.71.145:9405'   # JMX on simulator

  - job_name: 'app-http'
    metrics_path: /metrics
    static_configs:
      - targets:
          - '161.35.71.145:9091'
          - '161.35.71.145:9092'

  - job_name: 'app-node-exporter'
    static_configs:
      - targets: ['161.35.71.145:9101']

  - job_name: 'app-cadvisor'
    static_configs:
      - targets: ['161.35.71.145:8081']
