global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['68.183.210.76:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['68.183.210.76:8080']

  - job_name: 'app-jmx'
    # Removed scheme/tls_config so Prometheus uses plain HTTP
    static_configs:
      - targets:
          - 'minitwitdevops.live:9404'   # JMX on Minitwit
          - 'minitwitdevops.live:9405'   # JMX on Simulator

  - job_name: 'app-http'
    metrics_path: /metrics
    # Removed scheme/tls_config; now scraping over HTTP on the correct ports
    static_configs:
      - targets:
          - 'minitwitdevops.live:9094'   # blue
          - 'minitwitdevops.live:9095'   # green

  - job_name: 'app-node-exporter'
    # Removed scheme/tls_config so Prometheus uses plain HTTP
    static_configs:
      - targets:
          - 'minitwitdevops.live:9101'

  - job_name: 'app-cadvisor'
    # Removed scheme/tls_config so Prometheus uses plain HTTP
    static_configs:
      - targets:
          - 'minitwitdevops.live:8081'
