name: CI/CD for Java Application

on:
  workflow_dispatch:
  push:
    branches:
      - feat/monitoring

jobs:
  test-java:
      name: Build & Test Java
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Java 21
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 21

        - name: Build & run Maven tests
          run: mvn clean test -B

  lint-monitoring:
    name: Lint Prometheus & Docker-Compose
    runs-on: ubuntu-latest
    services:
      prometheus:
        image: prom/prometheus:latest
        options: --entrypoint ""  # so we can run promtool from this image
    steps:
      - uses: actions/checkout@v3

      - name: Lint Prometheus config
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro \
            prom/prometheus \
            promtool check config /etc/prometheus/prometheus.yml

      - name: Validate monitoring docker-compose
        run: docker-compose -f monitoring/docker-compose.yml config -q

  lint-app-compose:
    name: Validate App docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate app docker-compose.yml
        run: docker-compose -f docker-compose.yml config -q

  deploy:
    runs-on: ubuntu-latest
    needs: [test-java, lint-monitoring, lint-app-compose]
    if: needs.test-java.result == 'success' && needs.lint-monitoring.result == 'success' && needs.lint-app-compose.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy everything to one droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_APP_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key:      ${{ secrets.DROPLET_SSH_KEY_PRIVATE }}
          script: |
            set -e

            # 1) App
            cd ~/DevOps-2025                 
            git pull
            docker compose down
            docker compose up -d --build