name: CI/CD for Java Application

on:
  workflow_dispatch:
  push:
    branches:
      - feat/monitoring

jobs:
  # ──────────────────────────────────────────────────────────────────────────────
  # 1. Auto‐format Java and commit back if needed
  format-java:
    name: Spotless Apply & Commit
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: >-
        --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
        --add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED
    steps:
      - uses: actions/checkout@v3
        with:
          # allow committing back to PR branch
          persist-credentials: true
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Run Spotless (auto-format)
        run: mvn -B spotless:apply
      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: apply code formatting (Spotless)"
          branch: ${{ github.head_ref }}
          file_pattern: |
            src/**/*.java

  # ──────────────────────────────────────────────────────────────────────────────
  # 2. Lint Java with Checkstyle
  lint-java:
    name: Maven Checkstyle
    runs-on: ubuntu-latest
    needs: format-java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Run Checkstyle
        run: mvn -B verify --fail-at-end

  # ──────────────────────────────────────────────────────────────────────────────
  # 3. Lint Dockerfiles with Hadolint
  lint-docker:
    name: Hadolint Dockerfiles
    runs-on: ubuntu-latest
    needs: format-java
    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfile (app)
        run: docker run --rm -i hadolint/hadolint:latest < Dockerfile
      - name: Lint Dockerfile.api (simulator)
        run: docker run --rm -i hadolint/hadolint:latest < Dockerfile.api

  # ──────────────────────────────────────────────────────────────────────────────
  # 4. Lint Shell scripts with ShellCheck
  lint-shell:
    name: ShellCheck Scripts
    runs-on: ubuntu-latest
    needs: format-java
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint all *.sh
        run: |
          find . -name '*.sh' | xargs shellcheck --severity=error

  build-and-test:
    name: Build & Test App Endpoints
    runs-on: ubuntu-latest
    needs: [lint-java, lint-docker, lint-shell, format-java]
    if: needs.lint-java.result == 'success' && needs.lint-docker.result == 'success' && needs.lint-shell.result == 'success' && needs.format-java.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build app & simulator images
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            build minitwit simulator-api

      - name: Start app stack
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            up -d

      - name: Wait for `/health` to respond
        run: |
          timeout 60 bash -c "until curl -sf http://localhost:5000/health | grep -q '\"status\":\"ok\"'; do
            echo 'waiting…'
            sleep 5
          done"


      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test deps
        run: pip install requests

      - name: Run API tests
        run: python3 tests/api_tests.py

      - name: Tear down
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            down --volumes

  deploy:
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    needs: [build-and-test, lint-java, lint-docker, lint-shell, format-java]
    if: needs.build-and-test.result == 'success' && needs.lint-java.result == 'success' && needs.lint-docker.result == 'success' && needs.lint-shell.result == 'success' && needs.format-java.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy everything to one droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_APP_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key:      ${{ secrets.DROPLET_SSH_KEY_PRIVATE }}
          script: |
            set -e

            # 1) App
            cd ~/DevOps-2025                 
            git pull
            docker compose down
            docker compose up -d --build